name: Realtime Development Stats

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '0 */3 * * *' # time run auto

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: false
          SHOW_TIMEZONE: false
          SHOW_PROFILE_VIEWS: false
